###
GET http://localhost:3000
###
//auth queries
POST  http://localhost:3000/register
 Content-Type: application/json

 {
   "user_id": "5",
    "username":"David Stone",
    "password":"pass",
    "role":"user",
    "created_at": "2021-09-01",
    "updated_at": "2021-09-01"
 }
###
POST  http://localhost:3000/login
 Content-Type: application/json
 
 

 {
    "username":"David Stone",
    "password":"pass"
    
 }

###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/1
###
GET http://localhost:3000/usersWithBookings
###
GET http://localhost:3000/users/withBookings/5
###
GET http://localhost:3000/usersWithTickets
###
POST http://localhost:3000/users
Content-Type: application/json

{
    
  "full_name": "Jane Doe",
  "email": "janedoe@gmail.com",
  "contact_phone": "1234567890",
  "address": "1234 Main St, City, State, 12345",
  "role": "user",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
}
###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    
  "email": "John Doe@gmail"
}
###
DELETE http://localhost:3000/users/5

//vehicles queries
###
GET http://localhost:3000/vehicles
###
GET http://localhost:3000/vehicles/1
###
GET http://localhost:3000/vehiclesWithSpecs
###
GET http://localhost:3000/vehiclesWithSpecsAndFleet   
###
POST http://localhost:3000/vehicles
Content-Type: application/json

{
    
  "rental_rate": 100,
  "availability": "false",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
  
}
###
PUT http://localhost:3000/vehicles/2
Content-Type: application/json

{
    
  "availability": "true"
}
###
DELETE http://localhost:3000/vehicles/5

//vehicles specifications queries

###
GET http://localhost:3000/vehiclesSpecifications
###
GET http://localhost:3000/vehiclesSpecifications/1
###
POST http://localhost:3000/vehiclesSpecifications
Content-Type: application/json

{
  "vehicleSpec_id": 2,
  "vehicle_id": 1,
  "manufacturer": "Toyota",
  "model": "crown",
  "year": 2017,
  "fuel_type": "diesel",
  "engine_capacity": "3l",
  "transmission": "manual",
  "seating_capacity": 5,
  "color": "blue",
  "features": "salon"
}
###
PUT http://localhost:3000/vehiclesSpecifications/2
Content-Type: application/json

{
  "color": "red"
}

###
DELETE http://localhost:3000/vehiclesSpecifications/5

//Bookings queries
###
GET http://localhost:3000/bookings
###
GET http://localhost:3000/bookings/1

###
GET http://localhost:3000/bookingsWith-vehicle-and-user-and-payments
###
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "booking_id": 5,
  "user_id": 5,
  "vehicle_id": 7,
  "location_id": "5",
  "booking_date": "2021-09-01",
  "return_date": "2021-09-10",
  "total_amount": 1000,
  "booking_status": "pending",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
}

###
PUT http://localhost:3000/bookings/2
Content-Type: application/json

{
  "booking_status": "approved"
}

###
DELETE http://localhost:3000/bookings/5

//payments queries
###
GET http://localhost:3000/payments
###
POST http://localhost:3000/paymentsWithstripe
Authorization: Bearer STRIPE_SECRET_KEY
Content-Type: application/json

{
  "payment_id": 5,
  "booking_id": 5,
  "payment_date": "2021-09-01",
  "amount": 1000,
  "payment_status": "pending",
  "payment_method": "credit card",
  "transaction_id": "1234567890",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
}
###
GET http://localhost:3000/payments/1
###
POST http://localhost:3000/payments
Content-Type: application/json

{
  "payment_id": 5,
  "booking_id": 5,
  "payment_date": "2021-09-01",
  "amount": 1000,
  "payment_status": "pending",
  "payment_method": "credit card",
  "transaction_id": "1234567890",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
}

###
PUT http://localhost:3000/payments/2
Content-Type: application/json

{
  "payment_status": "approved"
}
###
DELETE http://localhost:3000/payments/5

//Customer support tickets queries
###
GET http://localhost:3000/ticket
###
GET http://localhost:3000/ticket/1
###
POST http://localhost:3000/ticket
Content-Type: application/json

{
  "ticket_id": 5,
  "user_id": 5,
  "subject": "Booking issue",
  "description": "I have a problem with my booking",
  "status": "pending",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
}
###
PUT http://localhost:3000/ticket/5
Content-Type: application/json

{
  "status": "resolved"
}
###
DELETE http://localhost:3000/ticket/5

//Locations queries
###
GET http://localhost:3000/location
###
GET http://localhost:3000/location/1
###
POST http://localhost:3000/location
Content-Type: application/json

{
  "location_id": 5,
  "name": "Nairobi",
  "address": "1234 Main St, City, State, 12345",
  "contact_phone": "1234567890",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
}
###
PUT http://localhost:3000/location/2
###
DELETE http://localhost:3000/location/5

//fleetMagement queries
###
GET http://localhost:3000/fleetManagement
###
GET http://localhost:3000/fleetManagement/1
###
post http://localhost:3000/fleetManagement
Content-Type: application/json

{
  "fleet_id": 5,
  "vehicle_id": 5,
  "acquisition_date": "2021-09-01",
  "depreciation_rate": 0.1,
  "current_value": 10000,
  "maintenance_status": "good",
  "status": "active",
  "created_at": "2021-09-01",
  "updated_at": "2021-09-01"
}