###
GET http://localhost:3000
###
//auth queries
POST  http://localhost:3000/register
 Content-Type: application/json
 
 {
   
    "username":"Mose",
    "password":"pass",
    "role":"user",
    "email":"mose@gmail.com",
    "address":"1234 Main St, City, State, 12345",
    "contact_phone":"1234567890"
    
 }
###
POST  http://localhost:3000/login
 Content-Type: application/json
 
 {
    "username":"sara",
    "role":"user",
    "password":"1234"
    
 }

###
GET http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXh4Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwOTAyODUyfQ.E4gyy_BYyqR8WIhUcaZaGK6N_4vyUfylwEXakq5ic3o
###
GET http://localhost:3000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXh4Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwODkzMDI1fQ.gEx0oV_4xZ5W4IwhOTnH5RqWpaRMWum3NwbMLEMSTpc
###
GET http://localhost:3000/usersWithBookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXh4Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwOTAyODUyfQ.E4gyy_BYyqR8WIhUcaZaGK6N_4vyUfylwEXakq5ic3o
###
GET http://localhost:3000/users/withBookings/72
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4
###
GET http://localhost:3000/usersWithTickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDAyMTZ9.L1qTPSfVagFQN4xLzMjy7mD6LIn95OB_-On8dgUs-Rg
###
GET http://localhost:3000/users/singleUserWithTickets/78
###
POST http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDAyMTZ9.L1qTPSfVagFQN4xLzMjy7mD6LIn95OB_-On8dgUs-Rg
Content-Type: application/json

{
    
  "full_name": "michell",
  "email": "michell@gmail.com",
  "contact_phone": "1234567890",
  "address": "1234 Main St, City, State, 12345",
  "role": "user"
  
}
###
PUT http://localhost:3000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTk2MjB9.kAqEo5FSXmwoq8fjocN6ESBkg8GlVI5vKigxaAssnXo
Content-Type: application/json

{
    
  "email": "JohnyDoe@gmail"
}
###
DELETE http://localhost:3000/users/26
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4

//vehicles queries
###
GET http://localhost:3000/vehicles
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDEzOTN9.XuUAP3Rj4r_ZULM7mAICmJLsCnhqvJyJka6DG4xIwX0
###
GET http://localhost:3000/vehicles/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDEzOTN9.XuUAP3Rj4r_ZULM7mAICmJLsCnhqvJyJka6DG4xIwX0
###
GET http://localhost:3000/vehiclesWithSpecs
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDEzOTN9.XuUAP3Rj4r_ZULM7mAICmJLsCnhqvJyJka6DG4xIwX0
###
GET http://localhost:3000/vehiclesWithSpecsAndFleet   
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4
###
POST http://localhost:3000/vehicles
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4
Content-Type: application/json

{
    
  "rental_rate": 100,
  "availability": "false"
  
  
}
###
PUT http://localhost:3000/vehicles/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4
Content-Type: application/json

{
    
  "availability": "true"
}
###
DELETE http://localhost:3000/vehicles/5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4

//vehicles specifications queries

###
GET http://localhost:3000/vehiclesSpecifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDE2NzF9.DPT3G1ioj2bEhaPJYxmtqt3qBpcF0g1iC5WHAeubE34
###
GET http://localhost:3000/vehiclesSpecifications/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDE2NzF9.DPT3G1ioj2bEhaPJYxmtqt3qBpcF0g1iC5WHAeubE34
###
POST http://localhost:3000/vehiclesSpecifications
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDE2NzF9.DPT3G1ioj2bEhaPJYxmtqt3qBpcF0g1iC5WHAeubE34
Content-Type: application/json

{
  "vehicleSpec_id": 5,
  "vehicle_id": 1,
  "manufacturer": "Toyota",
  "model": "crown",
  "year": 2017,
  "fuel_type": "diesel",
  "engine_capacity": "3l",
  "transmission": "manual",
  "seating_capacity": 5,
  "color": "blue",
  "features": "salon"
}
###
PUT http://localhost:3000/vehiclesSpecifications/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4
Content-Type: application/json

{
  "color": "red"
}

###
DELETE http://localhost:3000/vehiclesSpecifications/5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4

//Bookings queries
###
GET http://localhost:3000/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MDcxOTl9.85JgVHYowIcRPtTXk6rkhVDzenAqbN5mkxc4KSJoJ9s
###
GET http://localhost:3000/bookings/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXh5Iiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA4MDA5OTB9.Rgxzn1MwKstUlHmptOFqBf3SMSQ3biPxVpYn0IjD60o

###
GET http://localhost:3000/bookingsWith-vehicle-and-user-and-payments
###
GET http://localhost:3000/bookingsWith-vehicle-and-user-and-payments/5
###
POST http://localhost:3000/bookings
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MTUxMzh9.prHi1HAXgEPNnhQbA52EDVN95O0lBo6L8xsA3czyL4w
Content-Type: application/json

{
  
  "user_id": 27,
  "vehicle_id": 10,
  "location_id": "5",
  "booking_date": "2021-09-01",
  "return_date": "2021-09-10",
  "total_amount": 1000,
  "booking_status": "pending"
  
}

###
PUT http://localhost:3000/bookings/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4
Content-Type: application/json

{
  "booking_status": "approved"
}

###
DELETE http://localhost:3000/bookings/5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhkanlrdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcwMzk1OX0.zRAD4wgosjBfLVG3ftXpkTmbdEWd3rzB4DaCzATMm-4

//payments queries
###
GET http://localhost:3000/payments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MDc3NTJ9.dUWn-69q9UhlHla8FAxw2eTDmE7cDqJ47dWeLJigfe8
###
POST http://localhost:3000/paymentsWithstripe
Content-Type: application/json

{
  "amount": 1000,
  "payment-method": "credit card"
}
###
GET http://localhost:3000/payments/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MDc3NTJ9.dUWn-69q9UhlHla8FAxw2eTDmE7cDqJ47dWeLJigfe8
###
POST http://localhost:3000/payments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI
Content-Type: application/json

{
  "payment_id": 5,
  "booking_id": 5,
  "payment_date": "2021-09-01",
  "amount": 1000,
  "payment_status": "pending",
  "payment_method": "credit card",
  "transaction_id": "1234567890"
  
}

###
PUT http://localhost:3000/payments/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MDc3NTJ9.dUWn-69q9UhlHla8FAxw2eTDmE7cDqJ47dWeLJigfe8
Content-Type: application/json

{
  "payment_status": "approved"
}
###
DELETE http://localhost:3000/payments/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTg4MDJ9.J_jqk079MNt-5YerPnOyHf0DowNcwAWrZHTOSIN4lA8

###
post

//Customer support tickets queries
###
GET http://localhost:3000/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI

###
GET http://localhost:3000/ticket/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI

###
POST http://localhost:3000/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI
Content-Type: application/json

{
  "ticket_id": 5,
  "user_id": 5,
  "subject": "Booking issue",
  "description": "I have a problem with my booking",
  "status": "pending"
  
}
###
PUT http://localhost:3000/ticket/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI
Content-Type: application/json

{
  "status": "resolved"
}
###
DELETE http://localhost:3000/ticket/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI

//Locations queries
###
GET http://localhost:3000/location
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTg2NTd9.VrprJrGWwR_5SiCPFKY4MiMidVr4AmHTAs2c6ysu1Js
###
GET http://localhost:3000/location/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTg2NTd9.VrprJrGWwR_5SiCPFKY4MiMidVr4AmHTAs2c6ysu1Js
###
POST http://localhost:3000/location
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTg2NTd9.VrprJrGWwR_5SiCPFKY4MiMidVr4AmHTAs2c6ysu1Js
Content-Type: application/json

{
  "location_id": 5,
  "name": "Nairobi",
  "address": "1234 Main St, City, State, 12345",
  "contact_phone": "1234567890"
  
}
###
PUT http://localhost:3000/location/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI
###
DELETE http://localhost:3000/location/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI

//fleetMagement queries
###
GET http://localhost:3000/fleetManagement
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI
###
GET http://localhost:3000/fleetManagement/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI
###
post http://localhost:3000/fleetManagement
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXhpbWFzIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3OTc2OTV9.t2Yyl2SjZgmm_mRmKk7jKM40Le8dODFep94s91KNPjI
Content-Type: application/json

{
  "fleet_id": 5,
  "vehicle_id": 5,
  "acquisition_date": "2021-09-01",
  "depreciation_rate": 0.1,
  "current_value": 10000,
  "maintenance_status": "good",
  "status": "active"
  
}
###
DELETE http://localhost:3000/fleetManagement/1
###
POST http://localhost:3000/send-contact-email